### ISSUE TITLE
Unlinked references are incorrectly sticky from page to page

### ISSUE THREAD

**Issue by ThatAdamGuy** [athensresearch/athens#1177]
**Problem**
Unlinked references show references for earlier-viewed page when unlinked reference section is open when user navigates to an unrelated page

**Steps to reproduce**
1) Navigate to a page that has unlinked references
2) Expand the unlinked references section
3) Navigate to a page that has NO unlinked references
4) Note that the unlinked references section on that page is inappropriately showing the unlinked references for the FIRST page (e.g., unlinked references persist showing in subsequently-viewed pages)
5) Navigate to ANOTHER page that has NO unlinked references
6) Notice that -- *again* -- the page shows the unlinked references from the *first* page

If the user collapses and then again expands the unlinked references section on subsequent pages without linked references, the pages will then no longer (incorrectly) show the unlinked references from the first page.

**Athens Version**
b80

**Comment by datokrat** [comment]
Unlinked refs are stored in an atom, see [node-page-el](https://github.com/athensresearch/athens/blob/main/src/cljs/athens/views/pages/node_page.cljs#L526). This atom is not replaced when the shown page changes.

I have a fix that checks before rendering whether the block ID has changed. I'll post a link to a proposed fix in a second.

Why don't we store the linked references in `app-db` and avoid this tinkering with atoms? Probably because multiple pages can be visible (e.g., in the sidebar), so that global state is not suitable?

**Comment by datokrat** [comment]
Here is the fix: https://github.com/datokrat/athens/commit/a9357bdb5f91156c525bb377364ecd2ee63d8a3b

It basically adds another atom to the local state of the component to keep track of changes of the block UID, and when they occur, it resets the local state.

Since I'm new here: Is this the way this should be fixed -- and if yes, should I just create a pull request?

**Comment by tangjeff0** [comment]
> Why don't we store the linked references in app-db and avoid this tinkering with atoms? Probably because multiple pages can be visible (e.g., in the sidebar), so that global state is not suitable?

Good point! Yea, we can have multiple pages available at the same time, so it makes sense to couple linked refs to a local page. @datokrat
