### ISSUE TITLE
fix(blocks): prevent `indent` when already a leaf block, prevent `indent` and `unindent` when already a top-level child

### ISSUE THREAD

**Issue by tangjeff0** [athensresearch/athens#209]

**Comment by alaq** [comment]
Can this issue be assigned to @nthd3gr33 @itsrainingmani and myself @alaq? We are working on a solution together. Thank you!

**Comment by tangjeff0** [comment]
Can you comment @itsrainingmani so I can also assign this to you?

**Comment by itsrainingmani** [comment]
Hi Jeff

**Comment by nthd3gr33** [comment]
Found additional unexpected behavior when making the video demo:

Pressing `tab` on the top-level child:
- expected behavior: nothing
- actual behavior: destroys the block

Tested on Dynalist and Roam to double-check that the expected behavior is the same on those platforms.

Should I create a new issue or add this to this issue (my recommendation)? @itsrainingmani @alaq

**Comment by tangjeff0** [comment]
Add it to this issue @nthd3gr33. I think you can edit title as well

**Comment by tangjeff0** [comment]
closed by #228
