### ISSUE TITLE
Undo (ctrl/cmd+z) doesn't work on special characters like [ , ] , ( , or )

### ISSUE THREAD

**Issue by seltzered** [athensresearch/athens#559]
**Problem**

Doing an undo doesn't undo after typing one of the special characters - observed with [ , ] , ( , or ) characters

**Expected Behavior**

Undo should perform the undo action even when typing these characters

**Dependencies**

- Athens:1.0.0beta30
- macOS big sur

**To Reproduce**

see video
1) type one of the special characters
2) try undo (cmd+z or ctrl+z depending on platform)

**Screenshots**

https://user-images.githubusercontent.com/297435/105409453-56fd2080-5be5-11eb-977e-00ff30c900ab.mov

**Comment by tangjeff0** [comment]
Very good bug. Ctrl-z needs work. Thanks @seltzered

**Comment by datokrat** [comment]
The problem seems to be that the textarea value is set via `(set! (.-value target) new-value)`. This corresponds to `target.value = new-value` in JavaScript and seems to break the undo mechanism.

In the above fix I replaced these commands by calls to `execCommand`, as it is already the case in [surround-and-set](https://sourcegraph.com/github.com/athensresearch/athens@a11ea7b/-/blob/src/cljs/athens/views/blocks/textarea_keydown.cljs?subtree=true#L444:7), which is called when the user presses cmd+y etc. to surround text with `~~`.
