### ISSUE TITLE
Editing page title to existing page prompts merge

### ISSUE THREAD

**Issue by tangjeff0** [athensresearch/athens#61]
# Demo

![edit-page-title-prompt-merge](https://user-images.githubusercontent.com/8952138/82101211-e9096c80-96d9-11ea-9b29-c3e3922fb31b.gif)

**Comment by jelmerderonde** [comment]
I have a couple of questions before I start implementing this:

1. If I understand re-frame correctly, the flow should be something like this:
- Editing the title triggers the `:node/rename` event.
- If no page with `new-title` exists, proceed with the rename.
- Otherwise, set some state in de re-frame db to show the merge prompt. Depending on the user response trigger a new event to `:node/merge` or cancel the whole thing.
- If the user navigates away from the page before responding to the prompt, we should clear the state showing the prompt. Something to add to the `:navigated` event?
Am I on the right track with this?

2. What is a merge exactly? Should it be implemented as well or does it have its own issue?
