### ISSUE TITLE
Add Search Queries

### ISSUE THREAD

**Issue by Tamriel** [athensresearch/athens#644]
When a block contains the query string `{{[[query]]: {and: [[ex-A]] [[ex-B]]}}}`, all blocks containing the strings `ex-A` and `ex-B` should be embedded below the query block.

The article [Searching Roam With Queries](https://www.roamstack.com/roam-queries-primer/) describes this in detail.

**Comment by tangjeff0** [comment]
Agree something like this is needed, so we should keep this issue, but definitely don't like how Roam queries are implemented.

1. What is the underlying problem?
2. What is the solution space. Can the query interface actually map to a graph database?

**Comment by jtrakk** [comment]
Designing a query language is a very very big job and I don't know how much developer time will be dedicated to query-language design. 


There are a lot of graph query languages out there, from very simple to complex. At the simple end is [this blog post](https://www.headshift.com/our-blog/2006/02/03/tql-a-standard-syntax-for-mult/)'s proposed "TQL" which looks like `(foo|bar) + baz`. XPath or Cypher, for example, are much more complex.


It may be worth considering some meta-solutions:

1. picking an existing query language
2. designing a query-language plugin system, to allow users to import, develop, and experiment with alternative query languages within Athens

**Comment by agentydragon** [comment]
I'd propose just allowing people to issue Datascript queries against the database, and render the results nicely if they fit some format. For example, "if you issue a query that returns a single variable `?block`, then we'll render the blocks; if it's `?page`, we'll render page links".

# Pros
* no need to add extra layer above DB
* allows full power of Datascript
  * (this is particularly an improvement over Roam's `{{query}}`, which has a very limited vocabulary)

# Cons
* maybe security issues if running on server?
  * might need sanitization? (especially if executed outside client)
* hard to remove once added; if people can issue arbitrary queries, and the feature is taken away later, people's queries would break
 * so what I'd do would probably be initially add a big warning saying "this can break later", or even hide this behind a feature switch
* requires users to fiddle with underlying Datascript db instead of higher-level page/block structure
  * (but I expect power users would be okay with that)
