### ISSUE TITLE
Option to turn spell check off 

### ISSUE THREAD

**Issue by panura** [athensresearch/athens#727]
**The problem: There's no option to turn spell check off**

When Athens Research doesn't detect the language of the text, the spell checker flags every word as incorrect.

The simplest solution would be an option to turn the spell check off.

**Comment by jmartinezheras** [comment]
what about the option to select proofing language? This would be convenient for me as I write both in Spanish and English

**Comment by panura** [comment]
That would be great as well. But I don't really expect to get spell checking for small languages like Finnish.

**Comment by tangjeff0** [comment]
See also #564 and https://www.electronjs.org/docs/tutorial/spellchecker

**Comment by sid597** [comment]
As mentioned by jeff this issue is discussed in #727, so closing this.

**Comment by the-jb** [comment]
#564 is mainly about right-click action of spell check.
But I think this option is needed even if right-click action is added, because of appearance issue when reading.
Someone just want to disable this feature, leaving just misspelled words one intended.

So, I think this issue needed to be re-open, dealing separately from #564.
