### ISSUE TITLE
Roam edn import error 'Conflicting upsert'

### ISSUE THREAD

**Issue by nllz** [athensresearch/athens#961]
**Problem**
Error thrown when importing Roam database into Athens, import aborted.

Tried to export different version of the Roam database, to no avail. So there seems to be an issue in the database, but am not sure how to fix it. The problem seems to be an entry on October 29, but in my database there is no meaningful data there. So perhaps I could use sed (or smth similar) to remove the database entry?

**Screenshots/Demo**
![Screenshot from 2021-04-13 11-31-56](https://user-images.githubusercontent.com/4548727/114531276-0c230000-9c4c-11eb-9604-45ac80dddc31.png)

**Athens Version**
1.0.0-beta.68 AppImage on Ubuntu 20.10

**Comment by damonsk** [comment]
Getting the same - sadly I don't know clojure to be able to submit a fix but I've traced it back to the following:

In Athens I found this

`(defn update-roam-db-dates
  "Strips the ordinal suffixes of Roam dates from block strings and dates.
  e.g. January 18th, 2021 -> January 18, 2021"`

As a theory, I thought there may be some conflict around this.  Turns out I have a Roam entry for February 18, 2020.  I also have a roam entry for February 18th, 2020.

I merged the two in Roam and did a fresh export and I was able to import.  

Hope this helps isolate the issue.

**Comment by tangjeff0** [comment]
@nllz some people struggled with importing when they had a Daily Note from Roam on today's date. Try deleting today's date page in Roam and then importing into Athens.

**Comment by julionav** [comment]
This is related to #1135 and I think should be covered by my fix #1171

**Comment by julionav** [comment]
Can you tried to import again using version 1.0.0-beta.82 @nllz ?
